#common
spring:
    profiles:
        active: local # default 환경
    banner:
        charset: UTF-8
        location: 'classpath:config/banner.txt'
    profile:
        active: local
    jpa:
        hibernate:
            ddl-auto: none
        generate-ddl: false
        show-sql: true
    datasource:
        #type: org.apache.tomcat.jdbc.pool.DataSource
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: 'net.sf.log4jdbc.sql.jdbcapi.DriverSpy'
        url: 'jdbc:log4jdbc:mysql://localhost:3306/db_skeleton?characterEncoding=UTF-8&serverTimezone=UTC'
        username: ahnstar83
        password: faith
        tomcat:
            max-active: 1
            max-idle: 1
            min-idle: 1
            max-wait: 1
            initial-size: 1
            test-on-borrow: true
            test-while-idle: true
            validation-query: select 1
            time-between-eviction-runs-millis: 10000
    http:
        multipart:
            max-file-size: 5MB
            max-request-size: 100MB
            
management:
    health: 
        mongo: 
            enabled: true 
    endpoints: 
        health: 
            show-detail: always
        web: 
            exposure: 
                include: '*'
                        
server:
    port: 80
    context-path: '/'
    compression:
        enabled: true
        min-response-size: 2048
    display-name: 'Skeleton for SpringBoot2'
    error:
        include-stacktrace: never
        whitelabel:
            enabled: true
    tomcat:
        protocol-header: x-forwarded-proto
        accesslog:
            enabled: false
            pattern: common
            prefix: access_log
            suffix: .log
        max-threads: 0
        uri-encoding: UTF-8
    session:
        timeout: 600
        cookie:
            domain: .ahnstar.com
            path: '/'

logging:
    level:
        root: info
        org:
            springframework:
                core: error
                beans: error
                context: error
                web: error
        jdbc:
            sqlonly: error
            audit: error
            resultset: error
            resultsettable: error
            connection: error
            sqltiming: error
        com:
            ahnstar: debug
    pattern:
        console: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] %level: %c - %msg%n'

mail:
    host: 'smtp.naver.com'
    port: 465
    user: 'nalrary14'
    password: 'faith83!'
    sender: 'nalrary14@naver.com'
    receiver: 
      - csahn@mail2.eduwill.net
      - ahnstar83@gmail.com


###################################################################
# local 환경설정
---
spring:
    profiles: local
   
server:
    port: 8080
    session:
        timeout: 3600
logging:
    level:
        root: info
    com:
        ahnstar: info
        
        
        
###################################################################
# dev 환경설정
---
spring:
    profiles: dev

logging:
    level:
        root: info
    com:
        ahnstar: info
        
        
        
###################################################################
# stg 환경설정
---
spring:
    profiles: stg
        
logging:
    level:
        root: info
    com:
        ahnstar: info
        
        
        
###################################################################
# live 환경설정
---
spring:
    profiles: live

logging:
    level:
        root: error
    com:
        ahnstar: error
management: 
    health: 
        mongo: 
            enabled: false